### ISSUE TITLE
seaf-cli.py 是否可以只保留 diff

### ISSUE THREAD

**Issue by ZenithalHourlyRate** [prnake/Thu-Toolbox#2]
我是 seaf-cli 用户，日常通过[魔法途径](https://github.com/ZenithalHourlyRate/thuservices/blob/master/services.md#%E6%B8%85%E5%8D%8E%E4%BA%91%E7%9B%98)同步相关文件。

将 seaf-cli.py 与官方的 seaf-cli 相 diff，可见相关修改，应该是关键修改。

其余依赖均未做修改，感觉可以在项目中只保留主要 diff，其余依赖均通过包管理器进行，例如 Arch 有 seafile 的包，其中包含 seaf-daemon 等依赖。

同时在 repo 中分发 .so 的行为移植性欠佳。

**Comment by prnake** [comment]
Sloved

**Comment by ZenithalHourlyRate** [comment]
看起来 seaf-cli.py 依旧是完整的文件，感觉可以再分发一份 `seaf-cli.py.patch`，利用 
```
git diff /usr/bin/seaf-cli ./seaf-cli.py > seaf-cli.py.patch
```
生成，用户可以用patch工具自动修改（需要在readme中标明对应seaf-cli的版本），同时用户也容易审核相关代码

另：感觉可以向上游提交patch
另：pysearchpc与seafile.py与上游基本相同，可以将免安装版本单独放一个目录，然后将patch放在外面

**Comment by prnake** [comment]
有道理
